var projects = [
  {
    repoName:"Choose_your_own_adventure",
    projectName:"Choose your own Adventure",
    description:"A Minecraft-themed Choose Your Own Adventure Game",
    image:"images/chooseYourOwnAdventure.png",
    projectURL:"http://sallyhall.github.io/Choose_your_own_adventure",
    display:false,
  },
  {
    repoName:"Powell_Peralta",
    projectName:"Powell Peralta",
    description:"Created from a pdf.",
    image:"images/PowellPeralta.png",
    projectURL:"http://sallyhall.github.io/Powell_Peralta",
    display:true,
  },
  {
    repoName:"Surf_and_Paddle",
    projectName:"Surf & Paddle",
    description:"Recreation of a pdf.",
    image:"images/surfAndPaddle.png",
    projectURL:"http://sallyhall.github.io/Surf_and_Paddle",
    display:true,
  },
  {
    repoName:"crud-todo",
    projectName:"Todo List",
    description:"Todo list - made to practice CRUD.",
    image:"images/todos.png",
    projectURL:"http://sallyhall.github.io/crud-todo",
    display:true,
  },
  {
    repoName:"github-recreation",
    projectName:"Github Recreation",
    description:"Recreating my github profile.",
    image:"images/gitHub.png",
    projectURL:"http://sallyhall.github.io/github-recreation",
    display:true,
  },
  {
    repoName:"go-fish",
    projectName:"Go Fish",
    description:"Go fish game made using constructors.",
    image:"images/goFish.png",
    projectURL:"http://sallyhall.github.io/go-fish",
    display:true,
  },
  {
    repoName:"html-intro-layout",
    projectName:"Octodex",
    description:"Recreation of a portion of the Octodex",
    image:"images/octodex.png",
    projectURL:"http://sallyhall.github.io/html-intro-layout",
    display:false,
  },
  {
    repoName:"jQuery-photo-albums",
    projectName:"Photo Album",
    description:"Photo album made using jQuery.",
    image:"images/photoalbum.png",
    projectURL:"http://sallyhall.github.io/jQuery-photo-albums",
    display:false,
  },
  {
    repoName:"lovelace",
    projectName:"Juan on One",
    description:"Group chat project - using Ajax.",
    image:"images/chat.png",
    projectURL:"http://sallyhall.github.io/lovelace",
    display:true,
  },
  {
    repoName:"theDOM",
    projectName:"Calculator in the DOM",
    description:"Bonus project to make calculator in the DOM.",
    image:"images/calculator.png",
    projectURL:"http://sallyhall.github.io/theDOM",
    display:false,
  },
  {
    repoName:"theIronMenu",
    projectName:"The Iron Menu",
    description:"Group project with front and back end to create an editable and filterable menu.",
    image:"images/theIronMenu.png",
    projectURL:"",
    display:true,
  },
  {
    repoName:"chrome-extension",
    projectName:"Aww extension",
    description:"Chrome extension that displays thumbnails from the first page of a subreddit, linked back to the posts. Displays r/aww by default.",
    image:"images/chromeExtension.png",
    projectURL:"",
    display:true,
  }
]
