var projects = [
  {
    repoName:"Choose_your_own_adventure",
    projectName:"Choose your own Adventure",
    description:"A Minecraft-themed Choose Your Own Adventure Game",
    image:"",
    projectURL:"",
    tools:"",
  },
  {
    repoName:"Powell_Peralta",
    projectName:"Powell Peralta"
    description:"Created from a pdf.",
    image:"",
    projectURL:"",
    tools:"",
  },
  {
    repoName:"Surf_and_Paddle",
    projectName:"",
    description:"",
    image:""
    projectURL:"",
    tools:"",
  },
  {
    repoName:"crud-todo",
    projectName:"",
    description:"",
    image:""
    projectURL:"",
    tools:"",
  },
  {
    repoName:"github-recreation",
    projectName:"",
    description:"",
    image:""
    projectURL:"",
    tools:"",
  },
  {
    repoName:"go-fish",
    projectName:"",
    description:"",
    image:""
    projectURL:"",
    tools:"",
  },
  {
    repoName:"html-intro-layout",
    projectName:"",
    description:"",
    image:""
    projectURL:"",
    tools:"",
  },
  {
    repoName:"jQuery-photo-albums",
    projectName:"",
    description:"",
    image:""
    projectURL:"",
    tools:"",
  },
  {
    repoName:"lovelace",
    projectName:"",
    description:"",
    image:""
    projectURL:"",
    tools:"",
  },
  {
    repoName:"theDOM",
    projectName:"",
    description:"",
    image:""
    projectURL:"",
    tools:"",
  },
  {
    repoName:"theIronMenu",
    projectName:"",
    description:"",
    image:""
    projectURL:"",
    tools:"",
  },
  {
    repoName:"chrome-extension",
    projectName:"",
    description:"",
    image:""
    projectURL:"",
    tools:"",
  }
]
